kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
spec:
  storageClassName: mysql-persistent-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi