apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    app: mysql
data:
  base.cnf: |
    [mysqld]
    disabled_storage_engines="MyISAM,BLACKHOLE,FEDERATED,ARCHIVE,MEMORY"
    gtid_mode=ON
    enforce_gtid_consistency=ON
    binlog_checksum=NONE
    plugin_load_add='group_replication.so'
    loose-group_replication_unreachable_majority_timeout=10000
    loose-group_replication_autorejoin_tries=5
    loose-group_replication_member_expel_timeout=10000
