spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: book-scheduler
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    zookeeper:
      discovery:
        root: /services/gray-light
        register: false
#      dependencies:
#        query-service:
#          path: /services/gray-light/query-service
#          required: true

  quartz:
    properties:
      "org.quartz.threadPool.threadCount": "2"

server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: gray.light.*.entity
