apiVersion: v1
kind: Service
metadata:
  name: mysql-local-service
spec:
  ports:
    - name: mysql-default
      port: 3306
    - name: mysql-group-replication
      port: 33061
  clusterIP: None
  selector:
    server: mysql